[book]
title = "用Rust实现Lua解释器"
authors = ["Wu Bingzheng"]
language = "zh-cn"
multilingual = true
src = "src"

[output.html]
git-repository-url = "https://github.com/WuBingzheng/build-lua-in-rust"

[[output.i18n.translations]]
language = "en"
translators = ["Google Translate"]
title = "Build a Lua interpreter in Rust"
src = "translations/en"
